baseURL = "marcoman.github.io"
languageCode = "en-us"
title = "Marco's Hugo Site"
theme = "reveal-hugo"

publishDir = "../docs"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true