name: Test node project

# The source of this information is from my demo/github/actions/02-starting-project, which we'll see referenced later.
# See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on: [push]

jobs:
  job1:
    # For fun, I'm naming a specific ubuntu. Probably a best practice to be specific.
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        # Ha, I was right.  We want to be specific with the versions.
        # We do not require additonal configuration, and this means we can omit the with: keyword and its options
        uses: actions/checkout@v4

        # ensure we have node version 18
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: run test
        run: npm test
